name: Deploy Bot to Hostinger VPS

on:
  push:
    branches:
      - main  # change en "master" si ta branche principale s'appelle comme ça

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "/root/discord-bot"

      - name: Run deployment script on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root/discord-bot
            npm install
            pm2 restart bot || pm2 start index.js --name bot
